import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :insightnest, InsightnestWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Render terminates TLS at their load balancer and proxies plain HTTP to the container.
# force_ssl is intentionally omitted — enabling it would break Render's health checks,
# which hit the container's HTTP port directly without an X-Forwarded-Proto header.
# HSTS is enforced upstream by Render.

# Configure Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Insightnest.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# GDPR: anonymise IP addresses in all log output before they reach any sink.
# Masks last IPv4 octet and last 80 bits of IPv6.
config :logger, :default_handler, filters: [{Insightnest.Logger.IpFilter, :filter}]

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
